### ISSUE TITLE
Random reaction error

### ISSUE THREAD

**Issue by TDRMinecraft** [tdr-studios/DiscordSystem#13]
![image](https://user-images.githubusercontent.com/38729194/92022770-0ed78180-ed5c-11ea-8cef-96b910ce9ea4.jpeg)
It chooses a random Action Wehen already chooses

**Comment by DSeeLPYT** [comment]
Fixed in https://github.com/tdr-studios/DiscordSystem/commit/d7f8df625cd38cacd146755215632d6ffa708a39
